apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rag-nov6-1 
  janus-idp.io/tekton: rag-nov6-1
  backstage.io/kubernetes-id: rag-nov6-1
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: rag-nov6-1
resources: 
- application-dev.yaml