apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag-nov6-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag-nov6-1:840c7014ac912a621d3e18087829c735adc30c3e@sha256:de4e3811dc5837fe28e39a1bbf2b4ab3f9503409e1bf798bedb47b2bd737c6b5 # use pre-built to bootstrap 
          name: app-inference
